global using Xunit;
global using FluentAssertions;
global using Moq;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging.Abstractions;
global using Microsoft.Extensions.Options;
global using Mud.HttpUtils;
global using Mud.HttpUtils.Attributes;
global using Mud.Wechat.Abstractions;
// P0-b 起首批源文件落位：Mud.Wechat.Pay.Abstractions.Credential（签名串/RSA/AES-GCM/时间戳闸）。
// P0-c 增补：Configuration（商户配置 DTO）与 Extensions（AddPayApp 注册入口）。
// P1-a 增补：主包（接口 + PayModule/PayServiceBuilder/AddWechatPayApi）与 DataModels（Transactions 域 DTO）。
global using Mud.Wechat.Pay;
global using Mud.Wechat.Pay.Abstractions.Credential;
global using Mud.Wechat.Pay.Abstractions.Configuration;
global using Mud.Wechat.Pay.Abstractions.Exceptions;
global using Mud.Wechat.Pay.Abstractions.Extensions;
global using Mud.Wechat.Pay.DataModels.Bill;
global using Mud.Wechat.Pay.DataModels.Certificates;
global using Mud.Wechat.Pay.DataModels.Common;
global using Mud.Wechat.Pay.DataModels.Refund;
global using Mud.Wechat.Pay.DataModels.Transactions;
global using Mud.Wechat.Pay.Download;
global using Mud.Wechat.Pay.Extensions;
global using Mud.Wechat.Pay.Transactions;
global using System.Security.Cryptography;
global using System.Security.Cryptography.X509Certificates;
global using System.Text;
