<Project>
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0;net8.0;net10.0</TargetFrameworks>
		<Version>1.0.3</Version>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoDefaultExcludes>true</NoDefaultExcludes>
		<Copyright>© 2019-2025 Mud Studio Co.,Ltd.</Copyright>
		<Authors>Mud Studio</Authors>
		<Company>Mud Studio</Company>
		<LangVersion>13.0</LangVersion>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' or '$(TargetFramework)' == 'net9.0' or '$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'or '$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="System.Text.Json" Version="10.0.2" />
	</ItemGroup>	
</Project>
