<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Mud.HttpUtils.Generator" Version="2.0.9" PrivateAssets="all" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Mud.HttpUtils" Version="2.0.9" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Interfaces\" />
	</ItemGroup>

</Project>
