<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
		<PackageReference Include="FluentAssertions" Version="7.0.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Mud.Wechat.MiniProgram\Mud.Wechat.MiniProgram.csproj" />
		<ProjectReference Include="..\..\Mud.Wechat.MiniProgram.Abstractions\Mud.Wechat.MiniProgram.Abstractions.csproj" />
		<ProjectReference Include="..\..\Mud.Wechat.MiniProgram.DataModels\Mud.Wechat.MiniProgram.DataModels.csproj" />
	</ItemGroup>

</Project>