// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Wechat 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

#if NET8_0_OR_GREATER
using Mud.Wechat.Work.DataModels.Contacts.Batch;
using Mud.Wechat.Work.DataModels.Contacts.ContactRules;
using Mud.Wechat.Work.DataModels.Contacts.Department;
using Mud.Wechat.Work.DataModels.Contacts.Export;
using Mud.Wechat.Work.DataModels.Contacts.Tags;
using Mud.Wechat.Work.DataModels.Contracts.Users;
using Mud.Wechat.Work.DataModels.CorpGroup;
using Mud.Wechat.Work.DataModels.CorpGroup.ChainContacts;
using System.Text.Json.Serialization;

namespace Mud.Wechat.Work.DataModels;

/// <summary>
/// 企业微信数据模型 AOT JsonContext（对齐 FeishuApiResultJsonContext / {Module}JsonContext 模式）。
/// 经主包 <c>WechatJsonResolverExtensions</c> 合并进组件序列化管线。
/// </summary>
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(WechatWorkResponse))]
[JsonSerializable(typeof(WechatChatbotResponse<WechatWorkResponse>))]
[JsonSerializable(typeof(InternalAppAuthentication.GetTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetProviderTokenRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetProviderTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetSuiteTokenRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetSuiteTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetPreAuthCodeResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetPermanentCodeRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetPermanentCodeResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetAuthInfoRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetAuthInfoResponse))]
[JsonSerializable(typeof(ProviderAuthentication.SetSessionInfoRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetCustomizedAuthUrlRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetCustomizedAuthUrlResponse))]
[JsonSerializable(typeof(ProviderAuthentication.SessionInfo))]
[JsonSerializable(typeof(ProviderAuthentication.Agent))]
[JsonSerializable(typeof(ProviderAuthentication.EditionAgent))]
[JsonSerializable(typeof(ProviderAuthentication.Edition))]
[JsonSerializable(typeof(ProviderAuthentication.Privilege))]
[JsonSerializable(typeof(ProviderAuthentication.SharedFrom))]
[JsonSerializable(typeof(ProviderAuthentication.AuthCorpDetailInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthCorpDetailInfoExt))]
[JsonSerializable(typeof(ProviderAuthentication.CorpExName))]
[JsonSerializable(typeof(ProviderAuthentication.DealerCorpInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthUserInfo))]
[JsonSerializable(typeof(ProviderAuthentication.RegisterCodeInfo))]
[JsonSerializable(typeof(CorpTokenAuthentication.GetCorpTokenRequest))]
[JsonSerializable(typeof(CorpTokenAuthentication.GetCorpTokenResponse))]
[JsonSerializable(typeof(UserInfo))]
[JsonSerializable(typeof(UserSimpleInfo))]
[JsonSerializable(typeof(UserExtAttr))]
[JsonSerializable(typeof(UserExtAttrItem))]
[JsonSerializable(typeof(UserExtAttrText))]
[JsonSerializable(typeof(UserExtAttrWeb))]
[JsonSerializable(typeof(UserExternalProfile))]
[JsonSerializable(typeof(UserWechatChannels))]
[JsonSerializable(typeof(UserExternalAttrItem))]
[JsonSerializable(typeof(UserMiniProgram))]
[JsonSerializable(typeof(UserBizMailAlias))]
[JsonSerializable(typeof(UserDepartmentInfo))]
[JsonSerializable(typeof(CreateUserRequest))]
[JsonSerializable(typeof(UpdateUserRequest))]
[JsonSerializable(typeof(BatchDeleteUsersRequest))]
[JsonSerializable(typeof(GetUserIdByMobileRequest))]
[JsonSerializable(typeof(GetUserIdByEmailRequest))]
[JsonSerializable(typeof(ConvertUserIdToOpenIdRequest))]
[JsonSerializable(typeof(ConvertOpenIdToUserIdRequest))]
[JsonSerializable(typeof(ListUserIdsRequest))]
[JsonSerializable(typeof(InviteMembersRequest))]
[JsonSerializable(typeof(ListMemberAuthRequest))]
[JsonSerializable(typeof(CheckMemberAuthRequest))]
[JsonSerializable(typeof(ListSelectedTicketUserRequest))]
[JsonSerializable(typeof(CreateUserResponse))]
[JsonSerializable(typeof(CreatedDepartmentList))]
[JsonSerializable(typeof(CreatedDepartmentInfo))]
[JsonSerializable(typeof(GetJoinQrcodeResponse))]
[JsonSerializable(typeof(GetUserSimpleListResponse))]
[JsonSerializable(typeof(GetUserDetailListResponse))]
[JsonSerializable(typeof(ListUserIdsResponse))]
[JsonSerializable(typeof(GetUserIdByMobileResponse))]
[JsonSerializable(typeof(GetUserIdByEmailResponse))]
[JsonSerializable(typeof(ConvertUserIdToOpenIdResponse))]
[JsonSerializable(typeof(ConvertOpenIdToUserIdResponse))]
[JsonSerializable(typeof(InviteMembersResponse))]
[JsonSerializable(typeof(ListMemberAuthResponse))]
[JsonSerializable(typeof(MemberAuthInfo))]
[JsonSerializable(typeof(CheckMemberAuthResponse))]
[JsonSerializable(typeof(ListSelectedTicketUserResponse))]
[JsonSerializable(typeof(DepartmentInfo))]
[JsonSerializable(typeof(DepartmentIdInfo))]
[JsonSerializable(typeof(CreateDepartmentRequest))]
[JsonSerializable(typeof(UpdateDepartmentRequest))]
[JsonSerializable(typeof(CreateDepartmentResponse))]
[JsonSerializable(typeof(GetDepartmentListResponse))]
[JsonSerializable(typeof(GetChildDepartmentIdListResponse))]
[JsonSerializable(typeof(GetDepartmentResponse))]
[JsonSerializable(typeof(TagInfo))]
[JsonSerializable(typeof(TagMemberInfo))]
[JsonSerializable(typeof(CreateTagRequest))]
[JsonSerializable(typeof(UpdateTagNameRequest))]
[JsonSerializable(typeof(AddTagMembersRequest))]
[JsonSerializable(typeof(RemoveTagMembersRequest))]
[JsonSerializable(typeof(CreateTagResponse))]
[JsonSerializable(typeof(GetTagMembersResponse))]
[JsonSerializable(typeof(ChangeTagMembersResponse))]
[JsonSerializable(typeof(GetTagListResponse))]
[JsonSerializable(typeof(ContactRuleRange))]
[JsonSerializable(typeof(ContactRule))]
[JsonSerializable(typeof(CreateContactRulesRequest))]
[JsonSerializable(typeof(UpdateContactRulesRequest))]
[JsonSerializable(typeof(DeleteContactRulesRequest))]
[JsonSerializable(typeof(CreateContactRulesResponse))]
[JsonSerializable(typeof(UpdateContactRulesResponse))]
[JsonSerializable(typeof(GetContactRulesResponse))]
[JsonSerializable(typeof(BatchCallbackRequest))]
[JsonSerializable(typeof(BatchImportUsersRequest))]
[JsonSerializable(typeof(BatchImportPartiesRequest))]
[JsonSerializable(typeof(BatchJobResponse))]
[JsonSerializable(typeof(BatchTaskResultItem))]
[JsonSerializable(typeof(GetBatchJobResultResponse))]
[JsonSerializable(typeof(ExportRequest))]
[JsonSerializable(typeof(ExportTagUsersRequest))]
[JsonSerializable(typeof(ExportJobResponse))]
[JsonSerializable(typeof(GetExportResultResponse))]
[JsonSerializable(typeof(ExportDataFile))]
[JsonSerializable(typeof(ListAppShareInfoRequest))]
[JsonSerializable(typeof(GetCorpGroupTokenRequest))]
[JsonSerializable(typeof(TransferMiniProgramSessionRequest))]
[JsonSerializable(typeof(UnionidToExternalUserIdRequest))]
[JsonSerializable(typeof(UnionidToPendingIdRequest))]
[JsonSerializable(typeof(ExternalUserIdToPendingIdRequest))]
[JsonSerializable(typeof(AppShareCorpInfo))]
[JsonSerializable(typeof(ExternalUserIdInfo))]
[JsonSerializable(typeof(PendingIdResultItem))]
[JsonSerializable(typeof(ListAppShareInfoResponse))]
[JsonSerializable(typeof(GetCorpGroupTokenResponse))]
[JsonSerializable(typeof(TransferMiniProgramSessionResponse))]
[JsonSerializable(typeof(UnionidToExternalUserIdResponse))]
[JsonSerializable(typeof(UnionidToPendingIdResponse))]
[JsonSerializable(typeof(ExternalUserIdToPendingIdResponse))]
[JsonSerializable(typeof(ChainInfo))]
[JsonSerializable(typeof(ChainGroupInfo))]
[JsonSerializable(typeof(ChainGroupCorpInfo))]
[JsonSerializable(typeof(ChainImportFailedContact))]
[JsonSerializable(typeof(ChainImportFailedCorp))]
[JsonSerializable(typeof(ChainImportCorpItem))]
[JsonSerializable(typeof(ChainImportContactItem))]
[JsonSerializable(typeof(ImportChainContactsRequest))]
[JsonSerializable(typeof(GetChainGroupRequest))]
[JsonSerializable(typeof(GetChainCorpInfoListRequest))]
[JsonSerializable(typeof(GetChainCorpInfoRequest))]
[JsonSerializable(typeof(RemoveChainCorpRequest))]
[JsonSerializable(typeof(GetChainUserCustomIdRequest))]
[JsonSerializable(typeof(GetCorpSharedChainListRequest))]
[JsonSerializable(typeof(GetChainListResponse))]
[JsonSerializable(typeof(GetChainGroupResponse))]
[JsonSerializable(typeof(GetChainCorpInfoListResponse))]
[JsonSerializable(typeof(GetChainCorpInfoResponse))]
[JsonSerializable(typeof(ImportChainContactsResponse))]
[JsonSerializable(typeof(ChainImportResult))]
[JsonSerializable(typeof(GetChainImportResultResponse))]
[JsonSerializable(typeof(GetChainUserCustomIdResponse))]
[JsonSerializable(typeof(GetCorpSharedChainListResponse))]
public sealed partial class WechatWorkJsonContext : JsonSerializerContext
{
}
#endif
