// -----------------------------------------------------------------------
//  作者：Mud Studio  版权所有 (c) Mud Studio 2026
//  Mud.Wechat 项目的版权、商标、专利和其他相关权利均受相应法律法规的保护。
//  本项目主要遵循 MIT 许可证进行分发和使用。许可证位于源代码树根目录中的 LICENSE-MIT 文件。
//  不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目开发而产生的一切法律纠纷和责任，我们不承担任何责任！
// -----------------------------------------------------------------------

#if NET8_0_OR_GREATER
using System.Text.Json.Serialization;

namespace Mud.Wechat.Work.DataModels;

/// <summary>
/// 企业微信数据模型 AOT JsonContext（对齐 FeishuApiResultJsonContext / {Module}JsonContext 模式）。
/// 经主包 <c>WechatJsonResolverExtensions</c> 合并进组件序列化管线。
/// </summary>
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(WechatWorkResponse))]
[JsonSerializable(typeof(WechatChatbotResponse<WechatWorkResponse>))]
[JsonSerializable(typeof(InternalAppAuthentication.GetTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetProviderTokenRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetProviderTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetSuiteTokenRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetSuiteTokenResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetPreAuthCodeResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetPermanentCodeRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetPermanentCodeResponse))]
[JsonSerializable(typeof(ProviderAuthentication.GetAuthInfoRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetAuthInfoResponse))]
[JsonSerializable(typeof(ProviderAuthentication.SetSessionInfoRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetCustomizedAuthUrlRequest))]
[JsonSerializable(typeof(ProviderAuthentication.GetCustomizedAuthUrlResponse))]
[JsonSerializable(typeof(ProviderAuthentication.SessionInfo))]
[JsonSerializable(typeof(ProviderAuthentication.Agent))]
[JsonSerializable(typeof(ProviderAuthentication.EditionAgent))]
[JsonSerializable(typeof(ProviderAuthentication.Edition))]
[JsonSerializable(typeof(ProviderAuthentication.Privilege))]
[JsonSerializable(typeof(ProviderAuthentication.SharedFrom))]
[JsonSerializable(typeof(ProviderAuthentication.AuthCorpDetailInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthCorpDetailInfoExt))]
[JsonSerializable(typeof(ProviderAuthentication.CorpExName))]
[JsonSerializable(typeof(ProviderAuthentication.DealerCorpInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthInfo))]
[JsonSerializable(typeof(ProviderAuthentication.AuthUserInfo))]
[JsonSerializable(typeof(ProviderAuthentication.RegisterCodeInfo))]
[JsonSerializable(typeof(CorpTokenAuthentication.GetCorpTokenRequest))]
[JsonSerializable(typeof(CorpTokenAuthentication.GetCorpTokenResponse))]
[JsonSerializable(typeof(Users.UserInfo))]
[JsonSerializable(typeof(Users.UserSimpleInfo))]
[JsonSerializable(typeof(Users.UserExtAttr))]
[JsonSerializable(typeof(Users.UserExtAttrItem))]
[JsonSerializable(typeof(Users.UserExtAttrText))]
[JsonSerializable(typeof(Users.UserExtAttrWeb))]
[JsonSerializable(typeof(Users.UserExternalProfile))]
[JsonSerializable(typeof(Users.UserWechatChannels))]
[JsonSerializable(typeof(Users.UserExternalAttrItem))]
[JsonSerializable(typeof(Users.UserMiniProgram))]
[JsonSerializable(typeof(Users.UserBizMailAlias))]
[JsonSerializable(typeof(Users.UserDepartmentInfo))]
[JsonSerializable(typeof(Users.CreateUserRequest))]
[JsonSerializable(typeof(Users.UpdateUserRequest))]
[JsonSerializable(typeof(Users.BatchDeleteUsersRequest))]
[JsonSerializable(typeof(Users.GetUserIdByMobileRequest))]
[JsonSerializable(typeof(Users.GetUserIdByEmailRequest))]
[JsonSerializable(typeof(Users.ConvertUserIdToOpenIdRequest))]
[JsonSerializable(typeof(Users.ConvertOpenIdToUserIdRequest))]
[JsonSerializable(typeof(Users.ListUserIdsRequest))]
[JsonSerializable(typeof(Users.InviteMembersRequest))]
[JsonSerializable(typeof(Users.ListMemberAuthRequest))]
[JsonSerializable(typeof(Users.CheckMemberAuthRequest))]
[JsonSerializable(typeof(Users.ListSelectedTicketUserRequest))]
[JsonSerializable(typeof(Users.CreateUserResponse))]
[JsonSerializable(typeof(Users.CreatedDepartmentList))]
[JsonSerializable(typeof(Users.CreatedDepartmentInfo))]
[JsonSerializable(typeof(Users.GetJoinQrcodeResponse))]
[JsonSerializable(typeof(Users.GetUserSimpleListResponse))]
[JsonSerializable(typeof(Users.GetUserDetailListResponse))]
[JsonSerializable(typeof(Users.ListUserIdsResponse))]
[JsonSerializable(typeof(Users.GetUserIdByMobileResponse))]
[JsonSerializable(typeof(Users.GetUserIdByEmailResponse))]
[JsonSerializable(typeof(Users.ConvertUserIdToOpenIdResponse))]
[JsonSerializable(typeof(Users.ConvertOpenIdToUserIdResponse))]
[JsonSerializable(typeof(Users.InviteMembersResponse))]
[JsonSerializable(typeof(Users.ListMemberAuthResponse))]
[JsonSerializable(typeof(Users.MemberAuthInfo))]
[JsonSerializable(typeof(Users.CheckMemberAuthResponse))]
[JsonSerializable(typeof(Users.ListSelectedTicketUserResponse))]
[JsonSerializable(typeof(Department.DepartmentInfo))]
[JsonSerializable(typeof(Department.DepartmentIdInfo))]
[JsonSerializable(typeof(Department.CreateDepartmentRequest))]
[JsonSerializable(typeof(Department.UpdateDepartmentRequest))]
[JsonSerializable(typeof(Department.CreateDepartmentResponse))]
[JsonSerializable(typeof(Department.GetDepartmentListResponse))]
[JsonSerializable(typeof(Department.GetChildDepartmentIdListResponse))]
[JsonSerializable(typeof(Department.GetDepartmentResponse))]
[JsonSerializable(typeof(Tags.TagInfo))]
[JsonSerializable(typeof(Tags.TagMemberInfo))]
[JsonSerializable(typeof(Tags.CreateTagRequest))]
[JsonSerializable(typeof(Tags.UpdateTagNameRequest))]
[JsonSerializable(typeof(Tags.AddTagMembersRequest))]
[JsonSerializable(typeof(Tags.RemoveTagMembersRequest))]
[JsonSerializable(typeof(Tags.CreateTagResponse))]
[JsonSerializable(typeof(Tags.GetTagMembersResponse))]
[JsonSerializable(typeof(Tags.ChangeTagMembersResponse))]
[JsonSerializable(typeof(Tags.GetTagListResponse))]
[JsonSerializable(typeof(ContactRules.ContactRuleRange))]
[JsonSerializable(typeof(ContactRules.ContactRule))]
[JsonSerializable(typeof(ContactRules.CreateContactRulesRequest))]
[JsonSerializable(typeof(ContactRules.UpdateContactRulesRequest))]
[JsonSerializable(typeof(ContactRules.DeleteContactRulesRequest))]
[JsonSerializable(typeof(ContactRules.CreateContactRulesResponse))]
[JsonSerializable(typeof(ContactRules.GetContactRulesResponse))]
public sealed partial class WechatWorkJsonContext : JsonSerializerContext
{
}
#endif
